<?php

namespace VDMBundle\Repository;

/**
 * LoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoveRepository extends \Doctrine\ORM\EntityRepository
{
}
