_index:
    path:     /
    defaults: { _controller: "VDMBundle:Article:index" }
    methods:  GET

_new:
    path:     /new
    defaults: { _controller: "VDMBundle:Article:new" }
    methods:  [GET, POST]

_edit:
    path:     /{id}/edit
    defaults: { _controller: "VDMBundle:Article:edit" }
    methods:  [GET, POST]

_delete:
    path:     /{id}/delete
    defaults: { _controller: "VDMBundle:Article:delete" }
